spring:
  freemarker:
    expose-request-attributes: true

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/twitter}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:1}
    driver-class-name: org.postgresql.Driver

mail:
  properties:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

image:
  dir: "F:\\img"

weather:
  key: ${PRIVATE_KEY}
aws:
  secret: ${AWS_ACCESS_KEY}
  access: ${AWS_SECRET_KEY}
  bucket: logos-twitter-clone
  url: https://logos-twitter-clone.s3.eu-central-1.amazonaws.com/
